### ISSUE TITLE
inbound-saml tries to create entity with no token on http

### ISSUE THREAD

**Issue by SafinWasi** [GluuFederation/inbound-saml#146]
**Describe the bug**

While using `http` and creating a new trusted IDP through metadata URL, `inbound-saml` attempts to retrieve an authorization token from the token endpoint, which returns an error. `Inbound-saml` does not handle this and proceeds to try to create an entity with no token, leading to a `Failed to find entry` exception, which causes a status code `401` in `inbound-saml`.

**To Reproduce**

1. Install Gluu Server >= 4.4.0
2. Side install `inbound-saml` as described [here](https://github.com/GluuFederation/inbound-saml/blob/master/docs/getting_started.md).
3. When setting up Persistence API environment variables, ensure `INBOUND_SAML_OXTRUST_API_TOKEN_URL` is using `http`.
4. Start the SP Proxy Server in dev mode
5. Use `https://<hostname>/inbound-saml/trust-relation/metadata` to send a POST request to create a new trusted IDP ([example](https://github.com/GluuFederation/inbound-saml/blob/docs/openapi.yml))

**Expected behavior**
Returns status code `201`, new trusted IDP is added.

**Actual behavior**
Returns status code `500`: internal server error.

**Logs/Output**
A look at the SP Proxy Server console output reveals ` [ERROR]    Request failed with status code 401`. In addition, `oxtrust.log` reveals the following:

```
TRACE [qtp952562199-1073] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:189) - Validating RPT, resourceId: <client ID>, scopeIds: [oxtrust-api-write], authorization: Bearer undefined

```

**Additional context**
`inbound-saml` may need to either validate the bearer token (not accepting `undefined`) or raise an error for `http` connections.

**Comment by christian-hawk** [comment]
So, what's happening is that InboundSaml is unable to be authenticated in OxTrust Persistence Api when `INBOUND_SAML_OXTRUST_API_TOKEN_URL` configuration uses unsecured protocol (`http`) and works and uses secure (`https`).

So, basically, in **UMA Flow**, after receiving the ticket in the 401 response, when hitting the **token endpoint** (defined in `INBOUND_SAML_OXTRUST_API_TOKEN_URL`) oxauth (that authorizes the Oxtrust api) does not provide token.

This should happen conforming security protocols, provide token in an unsecured connection may expose access. 

As `https` is required, we may add a validation to this configuration property in [`OxTrustApiSettingsValidator`]( https://github.com/GluuFederation/inbound-saml/blob/master/packages/sp-proxy/src/interface-adapters/data/validators/OxTrustApiSettingsValidator.ts)

**Comment by christian-hawk** [comment]
**Token endpoint** SHOULD always use Secure protocol, according to [OAuth specs](https://www.rfc-editor.org/rfc/rfc6749):

> Since requests to the token endpoint result in the transmission of clear-text credentials (in the HTTP request and response), the authorization server MUST require the use of TLS as described in [Section 1.6](https://www.rfc-editor.org/rfc/rfc6749#section-1.6) when sending requests to the token endpoint.


Given that, I understand that we may deal with this issue adding an "https only" note at `INBOUND_SAML_OXTRUST_API_TOKEN_URL` and use the upcoming feature #152 that will use the endpoint provided from `.well-known` instead of manual configuration.

What are your thoughts @SafinWasi ?

**Comment by SafinWasi** [comment]
Enforcing  `https` would neatly solve this issue, so I think this is fine.
