### ISSUE TITLE
feat(trustRelation): change default SSO binding to `HTTP-Redirect`

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/inbound-saml#90]
Currently when we add a new TR, we look for `HTTP-POST` to set as default tr sso binding, then `HTTP-REDIRECT`, then any other.

We need to change this rule: https://github.com/GluuFederation/inbound-saml/blob/dc9c5b7551bb5572dfd1e10d9ee87293e394f4af/packages/sp-proxy/src/use-cases/helpers/pickDefaultSso.spec.ts#L34

So the first would be `HTTP-Redirect` , the second `HTTP-Post`, and then any other.

**Comment by kdhttps** [comment]
@christian-hawk added fix but not able to commit some other tests are failing
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
Test Suites: 2 failed, 3 passed, 5 total
Tests:       12 failed, 22 passed, 34 total
```
